# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plainte', '0003_calldata_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=50, verbose_name='Commune')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceDossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='numero')),
                ('libelle', models.CharField(max_length=50, verbose_name='libelle')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceLigne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='numero')),
                ('libelle', models.CharField(max_length=50, verbose_name='libelle')),
            ],
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
        migrations.RenameField(
            model_name='calldata',
            old_name='Nationnalite',
            new_name='nationnalite',
        ),
        migrations.RenameField(
            model_name='calldata',
            old_name='Nom',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='calldata',
            name='Numero',
        ),
        migrations.RemoveField(
            model_name='calldata',
            name='Operateur',
        ),
        migrations.RemoveField(
            model_name='calldata',
            name='Prenom',
        ),
        migrations.AddField(
            model_name='calldata',
            name='action_entreprise',
            field=models.TextField(max_length=200, null=True, verbose_name='action_entreprise'),
        ),
        migrations.AddField(
            model_name='calldata',
            name='contact',
            field=models.CharField(max_length=30, null=True, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='calldata',
            name='enregistre_par',
            field=models.CharField(max_length=50, null=True, verbose_name='enregistre_par'),
        ),
        migrations.AddField(
            model_name='calldata',
            name='heure_appel',
            field=models.TimeField(null=True, verbose_name='heure_appel'),
        ),
        migrations.AddField(
            model_name='calldata',
            name='langue_appel',
            field=models.CharField(max_length=20, null=True, verbose_name='langue_appel'),
        ),
        migrations.AddField(
            model_name='calldata',
            name='nature_appel',
            field=models.CharField(max_length=50, null=True, verbose_name='nature_appel'),
        ),
        migrations.AddField(
            model_name='calldata',
            name='operateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plainte.Operateur', verbose_name='Operateur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calldata',
            name='prenoms',
            field=models.CharField(default=1, max_length=50, verbose_name='Prenoms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calldata',
            name='qualite_appel',
            field=models.CharField(max_length=50, null=True, verbose_name='Qualite appel'),
        ),
        migrations.AddField(
            model_name='calldata',
            name='reponse_operatrice',
            field=models.TextField(max_length=100, null=True, verbose_name='reponse_operatrice'),
        ),
        migrations.AddField(
            model_name='calldata',
            name='suivi_plainte',
            field=models.CharField(max_length=50, null=True, verbose_name='suivi_plainte'),
        ),
        migrations.AddField(
            model_name='calldata',
            name='type_renseignement',
            field=models.CharField(max_length=50, null=True, verbose_name='type_renseignement'),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='Categorie_plainte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plainte.Categorie', verbose_name='Categorie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calldata',
            name='Commune',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plainte.Commune', verbose_name='Commune'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calldata',
            name='Profession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plainte.Profession', verbose_name='Profession'),
            preserve_default=False,
        ),
    ]
