# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plainte', '0004_auto_20180202_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calldata',
            old_name='Adresse',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='calldata',
            old_name='Categorie_plainte',
            new_name='categorie_plainte',
        ),
        migrations.RenameField(
            model_name='calldata',
            old_name='Commune',
            new_name='commune',
        ),
        migrations.RenameField(
            model_name='calldata',
            old_name='Date_constat',
            new_name='date_constat',
        ),
        migrations.RenameField(
            model_name='calldata',
            old_name='Mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='calldata',
            old_name='Objet_appel',
            new_name='objet_appel',
        ),
        migrations.RenameField(
            model_name='calldata',
            old_name='Profession',
            new_name='profession',
        ),
        migrations.RenameField(
            model_name='calldata',
            old_name='Recuperer',
            new_name='recuperer',
        ),
        migrations.RenameField(
            model_name='calldata',
            old_name='Reference_fiche',
            new_name='reference_fiche',
        ),
        migrations.RenameField(
            model_name='calldata',
            old_name='Telephone',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='calldata',
            name='Nature_appel',
        ),
        migrations.AddField(
            model_name='calldata',
            name='date_enregistrement',
            field=models.DateField(null=True, verbose_name='date enregistrement'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='profession',
            field=models.CharField(max_length=100, verbose_name='Profession'),
        ),
    ]
