# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fonction',
            field=models.CharField(max_length=200, null=True, verbose_name='fonction'),
        ),
    ]
