# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import utilisateur.models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_auto_20180118_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, storage=utilisateur.models.PictureStorage(), upload_to=utilisateur.models.upload_path, verbose_name='photo'),
        ),
    ]
