# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0008_auto_20180122_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nom_prenoms',
            field=models.CharField(max_length=100, null=True, verbose_name='nom et prenoms'),
        ),
    ]
